#!/usr/bin/env python
__requires__ = 'python-keyczar'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('python-keyczar', 'console_scripts', 'keyczart')()
    )
